# Default values for argo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

argo-cd:
  dex:
    enabled: false

  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      hosts:
        - argocd.localhost

minio:
  enabled: true
