# Default values for argo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

argo-cd:
  enabled: true
  dex:
    enabled: false

  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      hosts:
        - argocd.localhost

minio:
  enabled: true

  mode: standalone

  # Tweak the size of the disk usage for storage
  persistence:
    size: 5Gi

  replicas: 1

  resources:
    requests:
      memory: 128Mi

  buckets:
   - name: argo-logs
     policy: none
     # Purge if bucket exists already
     purge: false
     versioning: false
