# Default values for argo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

argo-cd:
  enabled: true
  dex:
    enabled: false

  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      hosts:
        - argocd.localhost

minio:
  enabled: true

  mode: standalone

  # Tweak the size of the disk usage for storage
  persistence:
    size: 5Gi

  replicas: 1

  resources:
    requests:
      memory: 128Mi

  consoleIngress:
    enabled: true
    path: /
    hosts:
      - minio.localhost

  users:
    ## Username, password and policy to be assigned to the user
    ## Default policies are [readonly|readwrite|writeonly|consoleAdmin|diagnostics]
    ## Add new policies as explained here https://docs.min.io/docs/minio-multi-user-quickstart-guide.html
    ## NOTE: this will fail if LDAP is enabled in your MinIO deployment
    ## make sure to disable this if you are using LDAP.
    - accessKey: console
      secretKey: console123
      policy: consoleAdmin

  buckets:
   - name: argo
     policy: none
     purge: false

postgresql:
  enabled: true

  resources:
    requests:
      memory: 64Mi

  postgresqlUsername: postgres
  postgresqlPassword: postgres
