---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {{ .Values.customResourceDefinition.kind | lower }}s.{{ .Values.customResourceDefinition.apiGroup }}
spec:
  group: {{ .Values.customResourceDefinition.apiGroup }}
  names:
    kind: {{ .Values.customResourceDefinition.kind }}
    listKind: {{ .Values.customResourceDefinition.kind }}List
    singular: {{ .Values.customResourceDefinition.kind | lower }}
    plural: {{ .Values.customResourceDefinition.kind | lower }}s
    shortNames:
      - {{ .Values.customResourceDefinition.abbreviation }}
  scope: Namespaced
  versions: {{ .Values.customResourceDefinition.versions | toYaml | nindent 4 }}
