{{- range $namespace := .Values.customResourceDefinition.namespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.customResourceDefinition.serviceAccount.name }}
  namespace: {{ $namespace }}
{{- end }}
