---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: geodatasets.antfield.nl
spec:
  group: antfield.nl
  names:
    kind: GeoDataset
    listKind: GeoDatasetList
    singular: geodataset
    plural: geodatasets
    shortNames:
      - gds
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - name
                - source
                - target
              properties:
                name:
                  type: string
                source:
                  type: string
                target:
                  type: string
